default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/snappea_development.sqlite3

test:
  <<: *default
  database: db/snappea_test.sqlite3

production:
  <<: *default
  database: db/snappea_production.sqlite3